# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCC3Zu7w4GSrsE3IMnhfuzxNRIiOkjr-
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from pathlib import Path
from PIL import Image

# Load DataFrames
df1 = pd.read_csv('/kaggle/input/chest-xrays-indiana-university/indiana_reports.csv')
df2 = pd.read_csv('/kaggle/input/chest-xrays-indiana-university/indiana_projections.csv')

# Create combined DataFrame
images_captions_df = pd.DataFrame({'imgs': [], 'captions': []})
for i in range(len(df2)):
    uid = df2.iloc[i]['uid']
    image = df2.iloc[i]['filename']
    index = df1.loc[df1['uid'] == uid]
    if not index.empty:
        index = index.index[0]
        caption = df1.iloc[index]['findings']
        if type(caption) == float:
            continue
        images_captions_df = pd.concat([images_captions_df, pd.DataFrame([{'imgs': image, 'captions': caption}])], ignore_index=True)

# Update image paths
p = '/kaggle/input/chest-xrays-indiana-university/images/images_normalized/'
images_captions_df['imgs'] = p + images_captions_df['imgs']

# Split DataFrames
train_, test_df = train_test_split(images_captions_df, test_size=0.10, shuffle=True, random_state=42)
train_df, val_df = train_test_split(train_, test_size=0.10, shuffle=True, random_state=42)

# Save DataFrames
train_df.to_csv('train.csv', index=False)
val_df.to_csv('val.csv', index=False)
test_df.to_csv('test.csv', index=False)

print(len(train_df))
print(len(val_df))
print(len(test_df))