# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCC3Zu7w4GSrsE3IMnhfuzxNRIiOkjr-
"""

import pandas as pd
from PIL import Image
from transformers import (
    VisionEncoderDecoderModel,
    AutoFeatureExtractor,
    AutoTokenizer
)
import tqdm
import nltk
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction

# Load data
val_df = pd.read_csv('val.csv')

# Load feature_extractor, tokenizer, and model
feature_extractor = AutoFeatureExtractor.from_pretrained('feature_extractor')
tokenizer = AutoTokenizer.from_pretrained('tokenizer')
model = VisionEncoderDecoderModel.from_pretrained('model')

# Generate captions
predicted_captions = []
for img_path in tqdm.tqdm(val_df['imgs']):
    img = Image.open(img_path).convert("RGB")
    features = feature_extractor(img, return_tensors="pt").pixel_values.to("cuda")
    caption = tokenizer.decode(model.generate(features, max_length=1024)[0], skip_special_tokens=True)
    predicted_captions.append(caption)

# Calculate BLEU score
generated_captions = [caption.split() for caption in predicted_captions]
ground_truth_captions = [[caption.split()] for caption in val_df['captions'].values]

smoothie = SmoothingFunction().method4
weights = (0.25, 0.25, 0.25, 0.25)
score = corpus_bleu(ground_truth_captions, generated_captions, weights=weights, smoothing_function=smoothie)
print(f'The BLEU Score is: {score}')