# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCC3Zu7w4GSrsE3IMnhfuzxNRIiOkjr-
"""

# Load data
df2 = pd.read_csv('/kaggle/input/chest-xrays-indiana-university/indiana_projections.csv')
df1 = pd.read_csv('/kaggle/input/chest-xrays-indiana-university/indiana_reports.csv')

# Create DataFrame for images and captions
images_captions_df = pd.DataFrame({'imgs': [], 'captions': []})
for i in range(len(df2)):
    uid = df2.iloc[i]['uid']
    image = df2.iloc[i]['filename']
    index = df1.loc[df1['uid'] == uid]

    if not index.empty:
        index = index.index[0]
        caption = df1.iloc[index]['findings']
        if type(caption) == float:
            continue
        images_captions_df = pd.concat([images_captions_df, pd.DataFrame([{'imgs': image, 'captions': caption}])], ignore_index=True)

# Update image paths
p = '/kaggle/input/chest-xrays-indiana-university/images/images_normalized/'
images_captions_df['imgs'] = p + images_captions_df['imgs']

# Split data
train_, test_df = train_test_split(images_captions_df, test_size=0.10, shuffle=True, random_state=42)
train_df, val_df = train_test_split(train_, test_size=0.10, shuffle=True, random_state=42)

# Save dataframes
train_df.to_csv('train_df.csv', index=False)
test_df.to_csv('test_df.csv', index=False)
val_df.to_csv('val_df.csv', index=False)